### ISSUE TITLE
msprior preprocess FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by ultranoise** [caillonantoine/msprior#4]
I have successfully trained V2, exported and run models with the following Colab: https://colab.research.google.com/drive/1ih-gv1iHEZNuGhHPvCHrleLNXvooQMvI with and without the --streaming option when exporting it. 

Both the streaming and the non-streaming versions can be loaded and run with nn~ in Max Msp. 

However it fails at prior learning using https://github.com/caillonantoine/msprior 

After installing all prerequisites (mac M1) and runing msprior preprocess with my non-streaming model I get a simple error:        
 
```                                                                                              
Using chunks of 23.78s
Found 560 audio files in /Users/.....***/datasets/IDMT-SMT-DRUMS-V2/audio/
0it [00:00, ?it/s](FileNotFoundError(2, 'No such file or directory'),)
```

Paths are ok and files exist. 

Here I am linking two models created with this Colab:

Without streaming:
https://drive.google.com/file/d/1WjqQjzcIvEzylIqnPHbgAAalwhQiZJ_O/view?usp=sharing

With streaming:
https://drive.google.com/file/d/1lNaU9Tg2laNe_CRy4qSWkOACCUoEFnuP/view?usp=sharing

They have been created with the IDMT-SMT Drums dataset: https://zenodo.org/record/7544164 using 147 epochs.

**Comment by caillonantoine** [comment]
I have preprocessed the IDMT dataset without any problem using the files you sent me. Can you give me the command you entered and that eventually led to the error ?

**Comment by caillonantoine** [comment]
This is indeed a `ffmpeg` related issue. On a side note, you should concat all wav files into a single one, as most files in this dataset have a duration that is less than the minimum msprior requires (i.e. 23s), and will not be used. You can use something like this

```python
import os
import pathlib
import shutil

dataset = "audio/"
wavs = map(str,pathlib.Path(dataset).glob("*.wav"))

os.makedirs("safe", exist_ok=True)

with open("list.txt", "w") as list:
    for i, wav in enumerate(wavs):
        name =f"audio_{i:04d}.wav"
        shutil.copy(wav, os.path.join("safe", name))
        list.write(f"file 'safe/{name}'\n")

os.system("ffmpeg -f concat -i list.txt -ac 1 -ar 44100 concatenated.wav")
```

**Comment by ultranoise** [comment]
yes, thanks. I had ffmpeg installed but the path was wrong. I reinstalled it using brew. 

I concatenated the files as you explained. Actually without it I got a List Out of Range Error as expected. Now I am preprocessing it and it finished with a

dataset length: 2:06:48.714739: : 0it [13:34, ?it/s]

(issue could be closed then?)

**Comment by caillonantoine** [comment]
:)
